baseURL = 'https://xn--wilmabruner-r8a.de/'
languageCode = 'de-de'
title = 'Spurensuche im Sylter Archiv... Zum Leben und Werk von Wilma Bräuner (1891-1985)'

theme = ["projektemacher-base"]
publishDir = "docs"
canonifyurls = true
disableKinds = ["term", "taxonomy"]
languagecode = "de"
defaultcontentlanguage = "de"
summaryLength = 40

[params]
    author = "Sylter Archiv"
    homeTitle = "Spurensuche im Sylter Archiv..."
    subTitle = "<span class='prefix'>Zum Leben und Werk von </span><a href='/'><img class='header-img' src='/images/signature.svg' alt='Unterschrift von Wilma Bräuner'></a> <a href='/'><span class='year'>(1891-1985)<span></a>"
    keywords = "blog, book, digitization, history, cultural history"
    Copyright = "false"
    homeList = true

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

[menu]
    [[menu.main]]
        name = "Veranstaltungsort"
        URL = "/location"
        weight = 1
        type = "meta"

    [[menu.main]]
        name = "Kontakt & Impressum"
        URL = "/about"
        weight = 2
        type = "meta"


#[languages]
#    [languages.de]
#        languagename = "Deutsch"
#
#        [languages.de.menu]
#
#            [[languages.de.menu.main]]
#                name = "Ort"
#                weight = 1
#                url = "location/"
#
#            [[languages.de.menu.main]]
#                name = "Über"
#                weight = 2
#                url = "about/"

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  [mediaTypes."application/x-qrcode-template"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.qrcode]
    mediaType = "application/x-qrcode-template"
    isPlainText = true
    isHTML = false
    baseName = "qrcode"
    notAlternative = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[imaging]
    quality = 95
