baseURL = 'https://xn--wilmabruner-r8a.de/'
languageCode = 'de-de'
title = 'Spurensuche im Sylter Archiv... Zum Leben und Werk von Wilma Bräuner (1891-1985)'

theme = ["projektemacher-base"]
publishDir = "docs"
canonifyurls = true
#disableKinds = ["taxonomy", "term"]
languagecode = "de"
defaultcontentlanguage = "de"
summaryLength = 40

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "content"
        target = "content"
#        excludeFiles = ["**/front/*", "**/back/*", "**/cover/*"]

[menu]

    [[menu.content]]
        name = "Hintergrund"
        URL = "/archive/"
        weight = 1
        type = "content"

    [[menu.content]]
        name = "Lebensstationen"
        URL = "/life/"
        weight = 2
        type = "content"

    [[menu.content]]
        name = "Künstlerisches Schaffen"
        URL = "/art/"
        weight = 3
        type = "content"

    [[menu.content]]
        name = "Naturschutz"
        URL = "/conservancy/"
        weight = 4
        type = "content"

    [[menu.main]]
        name = "Kontakt & Impressum"
        URL = "/about/"
        weight = 1
        type = "meta"

#    [[menu.main]]
#        name = "Rundgang / Bilder"
#        URL = "/tour/"
#        weight = 3
#        type = "meta"

#    [[menu.main]]
#        name = "Umsetzung"
#        URL = "/making-of/"
#        weight = 3
#        type = "meta"

    [[menu.main]]
        name = "Veranstaltungsort"
        URL = "/location/"
        weight = 4
        type = "meta"
#[languages]
#    [languages.de]
#        languagename = "Deutsch"
#
#        [languages.de.menu]
#
#            [[languages.de.menu.main]]
#                name = "Ort"
#                weight = 1
#                url = "location/"
#
#            [[languages.de.menu.main]]
#                name = "Über"
#                weight = 2
#                url = "about/"

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  [mediaTypes."application/x-qrcode-template"]
    suffixes = ["json"]
# See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.qrcode]
    mediaType = "application/x-qrcode-template"
    isPlainText = true
    isHTML = false
    baseName = "qrcode"
    notAlternative = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[imaging]
    quality = 95
